export const ADD_TODO = 'add_todo'
export const DELETE_TODO = 'delete_todo'
export const DELETE_ALL_TODO = 'delete_all_todo'
export const UNDO_TODO = 'undo_todo'
export const COMPLETE_TODO = 'complete_todo'
export const SHOW_ALL = 'show_all_todo'
export const SHOW_DONE = 'show_done_todo'
export const SHOW_UNDONE = 'show_undone_todo'
